#!/bin/bash

for f in $1/*; do
    echo "$f"
    ./a.out store "$f"
done

echo "Size of data"
du -sh $1/

echo "Size of data"
du -sh base_dir/

for f in $1/*; do
    echo "$f"
    ./a.out restore $(basename "$f")
    md5sum $(basename "$f")
done

